### ISSUE TITLE
Timecontrol doesn't redirect after saving

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/Timecontrol#10]
https://github.com/tsolucio/Timecontrol/blob/2945133b35495f26f48d4a2080dc2c5d11fa6a99/modules/Timecontrol/Save.php#L151

I create a timecontrol record from a project task, save it: white screen. It is saved, but the redirect doesn't work

**Comment by joebordes** [comment]
I'd say the problem is elsewhere. that "die" shouldn't even get executed ever

can you activate PHP errors and see if you get something on the screen that may give us some clue as to what is happening?

**Comment by joebordes** [comment]
I just tried this and it redirected correctly.

**Comment by Luke1982** [comment]
Did you do a fresh install? I have a pretty old installation that was updated. I think it has some remnants

**Comment by joebordes** [comment]
No, this is a very long-running coreBOS install I have for development that has external modules installed, timecontrol among others. I use that one for the external modules so I don't fill my main coreBOS development install with non-standard modules (making it impossible to run the unit test, for example).

**Comment by Luke1982** [comment]
OK, I'll have to do some more debugging then. I'll report back here if I have some more information.

**Comment by Luke1982** [comment]
This was only on a custom business action, I need to update that with new query parameters I think
