### ISSUE TITLE
PHP 8.* TypeError: mktime() expects integer for hour argument

### ISSUE THREAD

**Issue by denaldhushi** [tsolucio/Timecontrol#11]
Should make a check here if the `time_start` is not empty? because it produces a fatal error on `mktime` function.
https://github.com/tsolucio/Timecontrol/blob/489db2bcd0029ca933c487fd662d0ae6c4f2b2b5/modules/Timecontrol/DetailView.php#L27
![image](https://github.com/tsolucio/Timecontrol/assets/20266205/a79ea8d6-ba67-4e8d-8dee-15f4c1ff0c65)

**Comment by joebordes** [comment]
It shouldn't be empty. When you create a time-control record start time is mandatory.
The code that is failing is for the stopwatch, so it needs to know where to start. I'd say we set that value to "now" if it is empty.
Agree?

**Comment by denaldhushi** [comment]
Yes, setting the value to "now" makes sense.
