### ISSUE TITLE
'Continue' button takes me to edit existing screen

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/Timecontrol#3]
I updated to the latest coreBOS version and had to update Timecontrol as well. In the past, when I clicked 'continue' in a record that had been closed, a new record would open starting from the current time but keeping all other data. Now, I get sent to an 'edit existing' screen, so I have to create a new record every time. The URL I get sent to is simply the index.php.

**Comment by joebordes** [comment]
This should be working now. Update the DetailView.php, EditView.php and Timecontrol.php files.
Thanks for informing!
